name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1  
      - name: Initialize submodules
        run: git submodule init
      - name: Run HEMTT build
        run: hemtt release
      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: my-mod-latest
          path: release/zei-latest.zip